inherit_gem:
  standard: config/base.yml

require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0.2
  Exclude:
    - db/**/*
    - bin/**/*
    - vendor/**/* # for CI
    - tmp/*
    - public/**/*
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Performance/RedundantMerge:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/OptionalArguments:
  Enabled: false